spring:
  application:
    name: taxeasyfile-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  web:
    resources:
      add-mappings: false

jwt:
  secret: ${JWT_SECRET}
  expirationTime: ${JWT_EXPIRATION_TIME:3600000}
  refreshExpirationTime: ${JWT_REFRESH_EXPIRATION_TIME:86400000}

server:
  port: 8081
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.security: WARN
