spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
jwt:
  secret: "gW85(hkdp9%c((34&5#BrbMf#$45z6TcqEhP"
  expirationTime: 3600000  # 1 hour
  refreshExpirationTime: 7200000  # 2 hours
